### ISSUE TITLE
sf_run_report row limit

### ISSUE THREAD

**Issue by ijbthom** [StevenMMortimer/salesforcer#122] opened 2022-08-09 18:51 UTC
### Issue submission checklist

  - [ ] I have set `verbose=TRUE` function argument if possible. [It does not look like there are any issues here]
  
  - [ ] I have tried a few different function call arguments to see if I can workaround and/or isolate the issue (e.g. reviewing the output from the "SOAP" vs "REST" or the "Bulk 1.0" vs "Bulk 2.0" or tinkering with the `control` argument in the function call). [these arguments do not apply to the report functions]
  
  - [ ] I have taken a look at the unit tests directory [./tests/testthat/](./tests/testthat/) to see if my type of issue has been documented and tested.
  
  - [ ] I have included the version of R and any packages that are used 
  - [ ] 
  Thank you for considering these steps. It will speed up the process of resolving your issue.  
  
----

### Issue description

sf_run_report() calls to my reports in R only return the first 2000 records of each report. I work with many reports that have hundreds of thousands of records and I was really hoping to save time using salesforcer to pull these reports rather than exporting and saving each one individually to use in R. I don't think this is a bug on your end - I believe it is related to limitations of Salesforce API: https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_analytics_limitations.htm

It would be fantastic if you could build in a workaround to this Salesforce API limitation into your reports-related functions. I don't know how feasible it is, but figured I would ask because I'm sure it would be helpful to a lot of people. Thank you for reading.

## Session info
─ Session info ────────────────────────────────────────────────
 setting  value
 version  R version 4.2.0 Patched (2022-06-07 r82470 ucrt)
 os       Windows 10 x64 (build 19042)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/Los_Angeles
 date     2022-08-09
 rstudio  2022.02.2+485 Prairie Trillium (desktop)
 pandoc   NA

─ Packages ────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.2.0)
 cachem        1.0.6   2021-08-19 [1] CRAN (R 4.2.0)
 callr         3.7.0   2021-04-20 [1] CRAN (R 4.2.0)
 cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.0)
 crayon        1.5.1   2022-03-26 [1] CRAN (R 4.2.0)
 data.table    1.14.2  2021-09-27 [1] CRAN (R 4.2.0)
 DBI           1.1.2   2021-12-20 [1] CRAN (R 4.2.0)
 dbplyr        2.1.1   2021-04-06 [1] CRAN (R 4.2.0)
 devtools      2.4.4   2022-07-20 [1] CRAN (R 4.2.1)
 digest        0.6.29  2021-12-01 [1] CRAN (R 4.2.0)
 dplyr         1.0.9   2022-04-28 [1] CRAN (R 4.2.0)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.0)
 fansi         1.0.3   2022-03-24 [1] CRAN (R 4.2.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.2.0)
 fs            1.5.2   2021-12-08 [1] CRAN (R 4.2.0)
 generics      0.1.2   2022-01-31 [1] CRAN (R 4.2.0)
 glue          1.6.2   2022-02-24 [1] CRAN (R 4.2.0)
 htmltools     0.5.2   2021-08-25 [1] CRAN (R 4.2.0)
 htmlwidgets   1.5.4   2021-09-08 [1] CRAN (R 4.2.0)
 httpuv        1.6.5   2022-01-05 [1] CRAN (R 4.2.0)
 knitr         1.39    2022-04-26 [1] CRAN (R 4.2.0)
 later         1.3.0   2021-08-18 [1] CRAN (R 4.2.0)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.0)
 magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.2.0)
 memoise       2.0.1   2021-11-26 [1] CRAN (R 4.2.0)
 mime          0.12    2021-09-28 [1] CRAN (R 4.2.0)
 miniUI        0.1.1.1 2018-05-18 [1] CRAN (R 4.2.1)
 pillar        1.7.0   2022-02-01 [1] CRAN (R 4.2.0)
 pkgbuild      1.3.1   2021-12-20 [1] CRAN (R 4.2.1)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.0)
 pkgload       1.3.0   2022-06-27 [1] CRAN (R 4.2.1)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.2.0)
 processx      3.5.3   2022-03-25 [1] CRAN (R 4.2.0)
 profvis       0.3.7   2020-11-02 [1] CRAN (R 4.2.1)
 promises      1.2.0.1 2021-02-11 [1] CRAN (R 4.2.0)
 ps            1.7.0   2022-04-23 [1] CRAN (R 4.2.0)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.2.0)
 R6            2.5.1   2021-08-19 [1] CRAN (R 4.2.0)
 Rcpp          1.0.8.3 2022-03-17 [1] CRAN (R 4.2.0)
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.2.1)
 rlang         1.0.3   2022-06-27 [1] CRAN (R 4.2.1)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.2.0)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
 shiny         1.7.1   2021-10-02 [1] CRAN (R 4.2.0)
 stringi       1.7.6   2021-11-29 [1] CRAN (R 4.2.0)
 stringr       1.4.0   2019-02-10 [1] CRAN (R 4.2.0)
 tibble        3.1.7   2022-05-03 [1] CRAN (R 4.2.1)
 tidyselect    1.1.2   2022-02-21 [1] CRAN (R 4.2.0)
 urlchecker    1.0.1   2021-11-30 [1] CRAN (R 4.2.1)
 usethis       2.1.6   2022-05-25 [1] CRAN (R 4.2.1)
 utf8          1.2.2   2021-07-24 [1] CRAN (R 4.2.0)
 vctrs         0.4.1   2022-04-13 [1] CRAN (R 4.2.0)
 xfun          0.30    2022-03-02 [1] CRAN (R 4.2.0)
 xtable        1.8-4   2019-04-21 [1] CRAN (R 4.2.0)

**Comment by StevenMMortimer** [comment] 2022-08-22 14:00
Hi @ijbthom – Thanks for noting this. It's still on my list of things to figure out, if possible... See https://github.com/StevenMMortimer/salesforcer/issues/87 where I provided a couple of workaround ideas.

**Comment by tyler-widdison** [comment] 2023-05-25 21:59
Ditto on this, checking out #87

**Comment by StevenMMortimer** [comment] 2024-11-04 20:40
Closing since this issue is old and a duplicate of #87. It appears Salesforce is still enforcing the 2k row limit for records so the only way to get more is to re-create the logic of the report and run as a query, which is unfortunate.

**Closed by StevenMMortimer** 2024-11-04 20:40 UTC
