### ISSUE TITLE
API Bulk 2.0 doesn't return any ID fields

### ISSUE THREAD

**Issue by bellgriffin** [StevenMMortimer/salesforcer#37] opened 2019-09-06 20:04 UTC
When we create anything that is a child of another record type (i.e. create an opportunity on an account) then the returned data frame has 'NA' for all of the ID fields that were included to create the records (i.e. we get opportunity IDs back, but lose the account IDs).

**Comment by StevenMMortimer** [comment] 2019-09-16 20:06
@bellgriffin Please let me know if you're still having issues. Otherwise, I'll close this issue since I can't reproduce or help without more information. Thanks.

**Closed** 2019-12-29 13:50 UTC
Labels: could not reproduce, question or help
